In [ ]:
import numpy as np 
import scipy.io 

mat_path = r"../HW2_package/hw2_prob2.mat"
mat_file = scipy.io.loadmat(mat_path)

A = mat_file["A"]
d = mat_file["d"]
d_up = mat_file["d_up"]

def objective_function(A, x, d):
    return 0.5 * np.linalg.norm(A @ x - d)**2

def gradient(A, x, d):
    return A.T @ (A @ x - d)

def log_barrier(A, x, d_up, t):
    return -np.sum(np.log(d_up - A @ x)) / t

def log_barrier_gradient(A, x, d_up, t):
    return t * A.T @ (np.reciprocal(d_up - A @ x))

# Backtracking line search
def backtracking_line_search(A, x, d, d_up, t, alpha, beta, grad):
    step_size = 1.0
    while objective_function(A, x + step_size * grad, d) > objective_function(A, x, d) + alpha * step_size * np.dot(grad.T, grad):
        step_size *= beta
        if np.any(A @ (x + step_size * grad) >= d_up):  # Ensure that constraints are not violated
            step_size *= beta
    return step_size

# Gradient descent with log barrier and backtracking line search
def gradient_descent_with_log_barrier(A, d, d_up, t=1.0, max_iter=10000, alpha=0.01, beta=0.8):
    m, n = A.shape
    x = np.zeros((n, 1))  # Initial guess
    for i in range(max_iter):
        grad = gradient(A, x, d) + log_barrier_gradient(A, x, d_up, t)
        step_size = backtracking_line_search(A, x, d, d_up, t, alpha, beta, grad)
        x -= step_size * grad  # Update x
        print(grad)
        # Check for convergence (e.g., if step_size * grad is small enough)
    return x

gradient_descent_with_log_barrier(A, d, d_up, t = 1.5)



[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]